# continous integration : jenkins
jenkins:
  image: devopsopen/docker-ci-jenkins
  ports:
    - "7080:8080"
  expose:
    - "50000"
  environment:
    - JAVA_OPTS=-Djava.awt.headless=true
                -Djenkins.install.runSetupWizard=false
                -Dhttp.proxyHost=${http_proxy_host}
                -Dhttp.proxyPort=${http_proxy_port}
                -Dhttps.proxyHost=${https_proxy_host}
                -Dhttps.proxyPort=${https_proxy_port}
                -Duser.timezone=Asia/Shanghai
    - http_proxy=${http_proxy}
    - https_proxy=${https_proxy}
    - no_proxy=${no_proxy}
    - M2_PROXY_HOST=${http_proxy_host}
    - M2_PROXY_PORT=${http_proxy_port}
    - M2_NO_PROXY=${no_proxy}
    - DOCKER_HOST=${DOCKER_HOST}
  restart: never
